export default function Head() {
  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Mental Health Check-In</title>
      <meta name="description" content="Generated by Next.js" />
    </>
  );
}